blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/WHU4VdgWsd
    about: For quick questions, general discussion, and community chat
  - name: RackMind Website
    url: https://rackmind.ai
    about: Download the app and learn more
